[env:esp32-c3-oled]
platform = espressif32@6.9.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.filesystem = littlefs
extra_scripts = pre:scripts/ayres_compat.py
monitor_speed = 115200
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  olikraus/U8g2@2.36.15
  bblanchon/ArduinoJson@6.21.5
  ayresnet/AyresWiFiManager@2.3.0
